resilience4j:
  circuitbreaker:
    instances:
      redisClientCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        maxWaitDurationInHalfOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED

      postgresClientCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        maxWaitDurationInHalfOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED

      mongoClientCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        maxWaitDurationInHalfOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED


